### ISSUE TITLE
Gerenciamento de consultas

### ISSUE THREAD

**Issue by gbcastilho** [gabrielcarvalhais/MC426-SaudePublica#11]
Épico de gerenciamento de consultas feitas pelo sistema

> Como um paciente que usa o sistema de agendamentos para consultas em um hospital, preciso gerenciar as minhas consultas de forma eficiente e conveniente.

- [x] #15 
- [x] #16 
- [x] #19 
- [x] #20 
- [x] #21 
- [x] #22

**Comment by gabrielcarvalhais** [comment]
#25 #26 #27 #29
