### ISSUE TITLE
Filtrar agendamentos por tipo de consulta

### ISSUE THREAD

**Issue by gabrielcarvalhais** [gabrielcarvalhais/MC426-SaudePublica#12]
História para filtrar agendamentos por tipo de consulta.

> Como usuário do sistema (médico ou paciente), desejo filtrar os agendamentos do calendário pelo tipo de consulta, de forma que, possa visualizar os próximos agendamentos de maneira personalizada.
> Estimativa: 2.
> Critérios de aceitação:
> - Verifique se é possível filtrar a exibição de agendamentos por todos os tipos de consulta cadastrados no sistema;
> - Verifique se é possível atualizar os agendamentos conforme o filtro for sendo selecionado.

Épico:
- #9

**Comment by artguerra** [comment]
#25 #26 #27
