### ISSUE TITLE
Marcar consulta recorrente

### ISSUE THREAD

**Issue by gbcastilho** [gabrielcarvalhais/MC426-SaudePublica#15]
História de agendar consultas recorrentes

> Como um paciente, preciso ser capaz de marcar uma consulta recorrente, de forma a garantir um agendamento regular e consistente com o médico ou profissional de saúde.
> Estimativa: 2
> Critérios de Aceitação: 
> - Verifique se é possível que o paciente selecione a frequência da consulta recorrente, como semanal, quinzenal ou mensal, oferecendo opções predefinidas ou permitindo que o paciente insira um intervalo personalizado.
> - Verifique se, após a marcação da consulta recorrente, o sistema mostra no calendário as consultas nos dias recorrentes desejados.

Épico:
- #11

**Comment by gabrielcarvalhais** [comment]
#25 #26 #27
