### ISSUE TITLE
Editar consulta como um paciente

### ISSUE THREAD

**Issue by gbcastilho** [gabrielcarvalhais/MC426-SaudePublica#16]
História de editar consultas como um paciente

> Como um paciente, preciso ter a capacidade de editar os detalhes de uma consulta já agendada para corrigir informações ou reagendar, se necessário.
> Estimativa: 2
> Critérios de aceitação: 
> - Verifique se é possível que o paciente acesse a lista de suas consultas agendadas.
> - Verifique se o paciente pode selecionar uma consulta específica para edição.

Épico: 
- #11

**Comment by gabrielcarvalhais** [comment]
#25 #26 #27
