### ISSUE TITLE
Exibir os agendamentos de um funcionário

### ISSUE THREAD

**Issue by gabrielcarvalhais** [gabrielcarvalhais/MC426-SaudePublica#17]
História para exibir os agendamentos de um funcionário.

> Como usuário do sistema (médico), desejo visualizar meus agendamentos próximos e realizados em uma tela de calendário, de forma que, tenha um fácil acesso ao horário, dia e tipo das consultas futuras.
> Estimativa: 3.
> Critérios de aceitação:
> - Verifique se é possível exibir apenas os agendamentos do médico logado;
> - Verifique se é possível exibir o dia, horário e tipo da consulta nos itens internos do calendário.

Épico:
- #9

**Comment by artguerra** [comment]
#25 #26 #27
