### ISSUE TITLE
Editar consulta recorrente

### ISSUE THREAD

**Issue by gbcastilho** [gabrielcarvalhais/MC426-SaudePublica#19]
Hisória de editar consultas recorrentes

> Como um usuário (paciente ou médico), eu gostaria de poder editar as consultas recorrentes que tenho marcadas, de forma que esse compromisso periódico que tenho marcado possa ser reagendado para outro dia, ou que outras informações da consulta sejam alteradas.
> Estimativa: 2
> Critérios de aceitação:
> - Verifique se é possível editar consultas recorrentes e que a consulta recorrente teve suas informações alteradas corretamente.

Épico:
- #11

**Comment by gabrielcarvalhais** [comment]
#25 #26 #27
