### ISSUE TITLE
Remover consulta recorrente

### ISSUE THREAD

**Issue by gbcastilho** [gabrielcarvalhais/MC426-SaudePublica#20]
História para remover consultas recorrentes de um paciente.

> Como usuário do sistema (funcionário), desejo remover agendamentos recorrentes de um paciente, de forma que, possa lidar tranquilamente com agendamentos enganosos ou cancelamentos.
> Estimativa: 4.
> Critérios de aceitação:
> - Verifique se é possível remover agendamentos recorrentes de um paciente;
> - Verifique se é possível não exibir no calendário os agendamentos removidos.

Épico:
- #11

**Comment by gabrielcarvalhais** [comment]
#25 #26 #27 #29
