### ISSUE TITLE
Remover consulta de um paciente

### ISSUE THREAD

**Issue by gbcastilho** [gabrielcarvalhais/MC426-SaudePublica#21]
História para remover a consulta de um paciente.

> Como usuário do sistema (funcionário), desejo remover um agendamento específico de um paciente, de forma que, possa lidar tranquilamente com agendamentos enganosos ou cancelamentos.
> Estimativa: 3.
> Critérios de aceitação:
> - Verifique se é possível remover um agendamento específico de um paciente;
> - Verifique se é possível não exibir no calendário os agendamentos removidos.

Épico:
- #11

**Comment by gabrielcarvalhais** [comment]
#25 #26 #27 #29
