### ISSUE TITLE
Cadastrar nova consulta para paciente

### ISSUE THREAD

**Issue by gbcastilho** [gabrielcarvalhais/MC426-SaudePublica#22]
História para cadastrar (agendar) uma consulta nova de um paciente

> Como um paciente, preciso ter a capacidade de cadastrar uma nova consulta para mim, registrando os detalhes relevantes e agendando um horário adequado.
> Estimativa: 3
> Critérios de aceitação: 
> - O sistema deve fornecer campos para inserção das informações relevantes da consulta, como data, horário, duração estimada e motivo da consulta.
> - O sistema deve validar os campos de entrada para garantir que sejam preenchidos corretamente e que não haja conflitos com outros agendamentos.

Épico:
- #11

**Comment by gabrielcarvalhais** [comment]
#25 #26 #27
