### ISSUE TITLE
Code refactoring (Code smells)

### ISSUE THREAD

**Issue by gabrielcarvalhais** [gabrielcarvalhais/MC426-SaudePublica#38]
# Correção de code smells

Os code smells identificados no código estão descritos abaixo, separados por suas respectivas categorias.

### Shotgun Surgery

**Commit em que o code smell foi identificado e corrigido: ce472b7397bbf1fae0f44a541aeeb357308ecbee, b7e4386d5e510fff33f73917699ff6b7e636b763, 44e30847708fa87003c9b22c370ea1b87eed9900, 7596a006f3950ae9b15dfbb00c2dfec151e88129, 0e7bb731dd3ef714194c7b0cc5038c37047c0ae3** 

Foram identificadas nos arquivos `home.html` e `agendamento/index.html` gerações de menu que, na necessidade de uma mudança na disposição dos itens ou adicionar uma nova tela, exige que haja essas pequenas alterações em várias partes do código. Isso dificulta a manutenção e evolução do projeto, pois torna essa parte mais complexa de se alterar do que deveria.

Refatoramos criando uma _Inline Class_ `Menu` que se livra das redundâncias desses arquivos e gera um menu unificado descrito em `menu.html`.

### Large Method

**Commit em que o code smell foi identificado e corrigido: 2e80e44** 

Foi identificado, na classe `NotificacaoBackgroundService.cs`, que é a classe responsável pelos lembretes diários de consultas, que o método `ExecuteAsync` estava extremamente grande, com mais de 200 linhas, e continha dentro dele a lógica de buscar as consultas, enviar emails para os pacientes e enviar emails para os funcionários.

![image](https://github.com/gabrielcarvalhais/MC426-SaudePublica/assets/40214877/da3fdca3-3954-409d-afc0-444b763697e7)

Logo, foi alterado este método para que ele simplesmente chame outros três, que tem a responsabilidade de buscar os agendamentos do dia, enviar notificações para os paciente e enviar notificações para os funcionários.

**Commit em que o code smell foi identificado e corrigido: 088584f** 

Refatoração do arquivo `AgendamentoController.cs` com a separação de trechos grandes
de string para o html do e-mail em métodos separados por meio da técnica Replace Temp with Query e mudança na lógica de cadastros recorrentes de agendamento, reduzido para um único loop condicional por meio da técnica Decompose Conditional.

### Large Class

**Commit em que o code smell foi identificado e corrigido: 4f8e9ca**

Refatoração da página `index.html` de agendamentos, com a utilização do tratamento Extract Class, 
transferindo a responsabilidade de gerar os itens dinamicamente para o Javascript, 
reduzindo, assim, o tamanho do código html.

### Dead Code

**Commits em que o code smell foi identificado e corrigido: 17f3f7659293f45e982f41db41eed0ea74d7cc0c,  6856b379dfbf376184da69e79eaf6d4392a0c437, 62ab8c6 e bfb86cb** 

Uma série de blocos de código que não estavam mais sendo utilizados foram encontrados. Entre eles, alguns métodos que deixaram de ser usados conforme as features no backend foram feitas, métodos auxiliares utilizados por estes, imports que deixaram de ser utilizados nos arquivos e páginas que foram substituídas no HTML.

**Comment by gustavo-sacramento** [comment]
Correção de code smells #40

**Comment by gbcastilho** [comment]
Nova correção de code smells: #44
