### ISSUE TITLE
Calendário de agendamentos

### ISSUE THREAD

**Issue by gabrielcarvalhais** [gabrielcarvalhais/MC426-SaudePublica#9]
Épico de calendário de agendamentos do sistema.

> Como usuário do sistema (médico ou paciente), desejo ter acesso a uma tela em formato de calendário com os agendamentos previstos e realizados, de forma que, possa ter uma fácil visualização destas informações e filtra-las quando necessário.

- [x] #12 
- [x] #14 
- [x] #17

**Comment by artguerra** [comment]
#25 #26 #27
